-- -- Create the products table
-- CREATE TABLE products (
--     id INT PRIMARY KEY,
--     name VARCHAR(100),
--     supplier VARCHAR(100),
--     price DECIMAL(10, 2),
--     quantity INT,
--     remarks TEXT
-- );

-- -- Insert sample product values
-- INSERT INTO products (id, name, supplier, price, quantity, remarks) VALUES
-- (1, 'Laptop', 'TechCorp', 999.99, 50, 'Latest model with 16GB RAM'),
-- (2, 'Smartphone', 'PhoneInc', 699.99, 150, 'Includes a 1-year warranty'),
-- (3, 'Wireless Mouse', 'GadgetsPlus', 29.99, 200, 'Ergonomic design'),
-- (4, 'Mechanical Keyboard', 'KeyMasters', 89.99, 100, 'RGB lighting features'),
-- (5, 'USB-C Hub', 'ConnectorsRUs', 39.99, 75, 'Supports multiple devices'),
-- (6, 'Monitor', 'VisionTech', 249.99, 30, '4K resolution, 27 inches'),
-- (7, 'External Hard Drive', 'StorageMax', 89.99, 60, '2TB capacity'),
-- (8, 'Wireless Headphones', 'AudioBest', 149.99, 90, 'Noise-canceling feature'),
-- (9, 'Portable Charger', 'PowerUp', 19.99, 180, 'Fast charging capabilities'),
-- (10, 'Gaming Mouse', 'GameGear', 59.99, 120, 'High precision sensor'),
-- (11, 'Smartwatch', 'WearablesCo', 199.99, 70, 'Fitness tracking features'),
-- (12, 'Webcam', 'CamTech', 49.99, 140, '1080p resolution'),
-- (13, 'Bluetooth Speaker', 'SoundWave', 69.99, 110, 'Water-resistant'),
-- (14, 'Desk Lamp', 'LightBright', 39.99, 85, 'Adjustable brightness'),
-- (15, 'Router', 'NetConnect', 89.99, 50, 'High-speed Wi-Fi'),
-- (16, 'Tablet', 'TabWorld', 349.99, 40, 'Includes stylus'),
-- (17, 'Digital Camera', 'PhotoPro', 499.99, 25, 'DSLR with HD video'),
-- (18, 'VR Headset', 'RealityGear', 299.99, 30, 'Compatible with most systems'),
-- (19, 'Fitness Tracker', 'FitLife', 79.99, 150, 'Heart rate monitoring'),
-- (20, 'Game Console', 'PlayZone', 399.99, 45, 'Latest generation gaming');

-- SELECT DISTINCT name FROM products ;
-- SELECT COUNT(name) from products ;
-- SELECT AVG(price) from products ;
 -- SELECT AVG(price) from products ;SELECT SUM(price) from products ;
